[package]
name = "tap2mine"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"

[dev-dependencies]
snforge_std = "0.56.0"
assert_macros = "2.14.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[sncast.sepolia]
url = "https://starknet-sepolia-rpc.publicnode.com/"
account = "my_account"
accounts-file = "/Users/adran/.starknet_accounts/starknet_open_zeppelin_accounts.json"
block-explorer = "Voyager"
